// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkavrQ2U61yE64xymeBZdmGEs-L2WnhLU',
    appId: '1:329468218015:web:357e80a0d3ec9882c830aa',
    messagingSenderId: '329468218015',
    projectId: 'puifix',
    authDomain: 'puifix.firebaseapp.com',
    storageBucket: 'puifix.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDreoLJjB3Vu4mpO7t8TFBn4OwLa9JkE0Q',
    appId: '1:329468218015:android:f4384c2c111c68dbc830aa',
    messagingSenderId: '329468218015',
    projectId: 'puifix',
    storageBucket: 'puifix.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1muxd8j5wc7YlV0H5bgBTzUvDu6MBTg0',
    appId: '1:329468218015:ios:eb9a0f9460da3f72c830aa',
    messagingSenderId: '329468218015',
    projectId: 'puifix',
    storageBucket: 'puifix.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiPui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1muxd8j5wc7YlV0H5bgBTzUvDu6MBTg0',
    appId: '1:329468218015:ios:eb9a0f9460da3f72c830aa',
    messagingSenderId: '329468218015',
    projectId: 'puifix',
    storageBucket: 'puifix.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiPui',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkavrQ2U61yE64xymeBZdmGEs-L2WnhLU',
    appId: '1:329468218015:web:609dbbcfcac48eedc830aa',
    messagingSenderId: '329468218015',
    projectId: 'puifix',
    authDomain: 'puifix.firebaseapp.com',
    storageBucket: 'puifix.firebasestorage.app',
  );

}